### ISSUE TITLE
Video plays too fast when quest is in sleep mode [1.28]

### ISSUE THREAD

**Issue by christopher317** [Metalit/Replay#103]
I just rendered my PB for a 19 minute song ( The Sun, The Moon, The Star ) and noticed a massive audio de-sync at the end.
Most of the render is fine, but after 17 minutes and 10 seconds the audio starts rapidly falling behind the video.
I am using a older version of beat saber and thus the mod ( 1.28 ) because threes still a few mods that aren't quite up to date that i need, but with Beat Leader stopping support of it I'm gonna update soon, I'll close the issue if it turns out that the bug has already been fixed in the 1.37 version. ( If someone else can test before I update that would be great. )

The audio is in more or less perfect sync for the first 5 seconds of the clip and then gets more and more delayed as it goes on.

https://github.com/user-attachments/assets/442c3c3c-ada8-45da-8755-206bc63b857e

I have a feeling this is related to #101 because I'm pretty sure the render time was around 5 hours, an hour above the quest 3's maximum no sleep period.

**Comment by Metalit** [comment]
1.28 is no longer supported, however the next update for 1.37 will include an extra measure to prevent devices from going to sleep
