### ISSUE TITLE
Chains and Arcs

### ISSUE THREAD

**Issue by Manleyne** [Metalit/Replay#13]
In some replays, chains and arcs will be displayed incorrectly.

Check the top score here: https://www.beatleader.xyz/leaderboard/global/230dc91/1

**Comment by AKASGaming** [comment]
Can you please stop making separate issues and just put them all into one

**Comment by Manleyne** [comment]
[Example](https://streamable.com/houfod)

**Comment by Manleyne** [comment]
i can’t believe [Mapping Extensions](https://github.com/rcelyte/MappingExtensions/issues/3) would do this
