### ISSUE TITLE
Anti Aliasing and Smoke Settings

### ISSUE THREAD

**Issue by Manleyne** [Metalit/Replay#17]
Add settings for `0x`, `2x`, `4x`, `8x` AA some time 💖

**Comment by Metalit** [comment]
Maybe add smoke setting sometime too

**Comment by DawnXofXFear** [comment]
smoke setting is not needed.
smoke can be enabled in any tweaks.

**Comment by Metalit** [comment]
Added anti aliasing setting for renders, along with bloom, so that AnyTweaks isn't needed in rendering anymore.
