### ISSUE TITLE
Game Not Launching With Hollywood

### ISSUE THREAD

**Issue by Manleyne** [Metalit/Replay#24]
After installing Hollywood through BMBF, there is a high chance of the game then getting consistently stuck on the launch screen. If it doesn’t at first, syncing with BMBF can also have a chance of causing it. 

This *might* be an issue with BMBF, as installing it manually has worked 100% of the time.

**Comment by Metalit** [comment]
I haven't heard anything about this since so it seems like it's probably fine at this point.
