### ISSUE TITLE
Noodle Note Detection

### ISSUE THREAD

**Issue by Manleyne** [Metalit/Replay#30]
Specifically [NULCTRL](https://beatsaver.com/maps/ed2a) will have all of it’s notes not be registered.

This is possibly caused by the anti-quest protection method used. It finds a way for no notes to spawn without NE installed, since nothing used to stop you from playing NE maps without NE on quest.

**Comment by Manleyne** [comment]
muahahahahahahaha
![A8102ECB-A2C0-42E8-82D9-7A85887A67A7](https://user-images.githubusercontent.com/83431062/194414679-a65c4066-fea4-4b48-bcf3-30113c5aee66.jpeg)

**Comment by NSGolova** [comment]
This is definitely Quest BL recorder issue. All the replays from the PC on this map replaying correctly.
Will be fixed in the recorder and old replays will be fixed on the server.

**Comment by Manleyne** [comment]
BL issue
