### ISSUE TITLE
Beat Leader Replay Corruption 

### ISSUE THREAD

**Issue by Manleyne** [Metalit/Replay#31]
On rare occasions, Replay can cause BeatLeader to fail to upload a new highscore and display this message:
![6E1923CF-AD03-44A1-87EC-A3DA4E9715F7](https://user-images.githubusercontent.com/83431062/194882443-e2dbea56-3238-4d8b-952f-af53031613ba.jpeg)

BeatLeader will still have saved the replay and will be viewable with Replay, but all notes will not be registered in the replay.

**Comment by Metalit** [comment]
Resolved
