### ISSUE TITLE
[Hollywood] Bottom half of render seems to "glitch" or "wiggle" when hitting a note.

### ISSUE THREAD

**Issue by Koreami** [Metalit/Replay#40]
In a render, it appears that the bottom half of the render (around the health bar) seems to "wiggle" or "glitch" slightly whenever a note gets cut. This doesn't need to necessarily be fixed at the moment, but it's a little something that would make renders look a little bit better.

Btw great job on this mod! It's absolutely amazing, thank you for your hard work. ^^

An example of this "wiggle" effect can be found in this video: https://youtu.be/PpHtG6ZTV1U

**Comment by Metalit** [comment]
That's one of the PC graphics options available with renders known as shockwaves. It's entirely intended but is configurable in replay's mod settings, just like PC walls and mirrors, if you would rather disable it
