### ISSUE TITLE
Feature Req: AnyTweaks for Rendering

### ISSUE THREAD

**Issue by but2002** [Metalit/Replay#41]
There are obvious issues with certain high intensity maps for Noodle Extensions, so having certain rendering features toned down makes sense for playing, but it would be fantastic for the render feature to integrate with AnyTweaks to enable things like bloom or any other optional graphical tweaks.

_NE maps look remarkably better with bloom enabled due the appearance of walls_

**Comment by Metalit** [comment]
As far as I know, you can just enable bloom in AnyTweaks and it will show up while rendering. Is that not the case?

**Comment by but2002** [comment]
It absolutely is, but buried so deep in menus it's annoying to toggle.

**Comment by Metalit** [comment]
Unfortunately that sort of mod compatibility is a bit too much of a pain on both ends to implement an anytweaks setting into the replay menu, so I don't think this will be getting streamlined anytime soon
