### ISSUE TITLE
Clicking Continue while pausing in a replay crashes the game...

### ISSUE THREAD

**Issue by XCraftTM** [Metalit/Replay#43]
Tried out the Replay function and noticed that while you pause a replay you are able to change the speed and time of the play but if you click too quickly on the bar then it crashes your game...

So back to the real problem... Noticed that when you change something in the pause screen and then press continue the game crashes in any replay i tried it in.

Could only be my problem but idk.

Mod Version: https://github.com/Metalit/Replay/releases/tag/0.1.0
Mods: https://i.imgur.com/yr08Lj9.png
Libs: https://i.imgur.com/WTWDfIg.png

**Comment by XCraftTM** [comment]
Update: Just tried it with 0.1.1 and still crashes when just clicking continue in any replay without having to even change a setting.

**Comment by XCraftTM** [comment]
[GlobalLog_3_14_0.log](https://github.com/Metalit/Replay/files/9908806/GlobalLog_3_14_0.log)
Here is the GlobalLog of the Crash maybe it will help.

**Comment by CGray1234** [comment]
It's most likely caused by MoreByCore. Disable that, and see if it works.

**Comment by XCraftTM** [comment]
Thanks it fixed the Problem!
