### ISSUE TITLE
Walls have distortion, but still look like quest walls instead of pc walls

### ISSUE THREAD

**Issue by mapletoastt** [Metalit/Replay#47]
Title pretty much explains the whole issue. I’ll attach a video with the funky walls.

**Comment by mapletoastt** [comment]
For whatever reason I can’t attach a video. I’ll send a few screenshots instead
![958B8A49-8007-4A6B-810E-361A6167FDE8](https://user-images.githubusercontent.com/71468696/204654405-d104148a-ba53-40bc-8f1b-b1d865f9ae20.png)
![253B142A-9736-4886-B452-74F82A8208CC](https://user-images.githubusercontent.com/71468696/204654414-92c46660-87bc-4571-9c63-fc564ee6b82b.png)

**Comment by Metalit** [comment]
I don't know as I haven't played on PC, but are you sure it isn't just that the environment there doesn't have anything to be distorted and that's why it looks odd?

**Comment by mapletoastt** [comment]
Aren't pc walls supposed to have those weird distorted borders? Maybe I'm just crazy but I'm pretty sure that's not what pc walls are supposed to look like

**Comment by Metalit** [comment]
It might be bloom, which unfortunately wasn't possible for me to implement as a render option. Maybe try with anytweaks though as I believe it's compatible.

**Comment by mapletoastt** [comment]
Yep, adding bloom worked!

**Comment by CGray1234** [comment]
Turning on "disable fake glow" in Qosmetics-Boxes should also fix that :)
