### ISSUE TITLE
NE Movement Doubled

### ISSUE THREAD

**Issue by CreeperCrafter979** [Metalit/Replay#58]
I updated from 1.25.1 to 1.28 and found that any player movement from NoodleExtensions is now doubled while watching a replay in smooth camera or third person mode. This bug is also seen in the render process if you leave the screen enabled, but it does not appear in the final video. 
If you're moved upwards by 10 feet, Replay's camera will move upwards 20 feet and lose track of your sabers and avatar. If you're spun in a complete circle, Replay's camera will move twice the speed to instead make 2 full rotations. It seems as though the NE offset is first applied to the player, but then again to Replay's camera. I'd guess this could be fixed on Replay's side by applying counter movement to the camera or calculating the camera position from the world origin instead of the player position.
[Demonstration video](https://youtu.be/6jTGTGv1ZvU)

Note in the video that [debris is also failing to spawn in replays](https://github.com/Metalit/Replay/issues/51), or is lasting for only a single frame. I configured DebrisTweaks with negative values so the recording without Replay shows debris oddly zooming off in the distance, but both the NE movement and debris bugs persist after disabling all other unnecessary mods.

**Comment by Metalit** [comment]
Found the issue, just an accidental local position. Should be fixed in the next release.
