### ISSUE TITLE
The Spectrogram Does NOT Move In The Render

### ISSUE THREAD

**Issue by maxplayz2746** [Metalit/Replay#61]
The Spectrogram Does NOT Move In The Render And It Just Looks Very Odd If There Is A Way To Fix This Please Let Me Know

**Comment by maxplayz2746** [comment]
I have Video Clip

https://user-images.githubusercontent.com/84992927/234434320-648dd034-3c2b-4387-a285-f034efb12b44.mp4

**Comment by Metalit** [comment]
Yes I'm aware of this issue, it's to do with how replay mutes the audio. I have an idea as to how to fix it but it's somewhat low priority

**Comment by Metalit** [comment]
Fixed with 45d81c537044cb316dcc1df7eff167f728e3e8c4 (in the next release)
