### ISSUE TITLE
Rendering Queue 1.28 Quest 2

### ISSUE THREAD

**Issue by Andrey446** [Metalit/Replay#62]
When adding two songs to the queue.
I click on render and nothing happens.
All I see during the rendering of several songs is:
1) A black screen while it does not render anything.
2)Departure from the game.

**Comment by Metalit** [comment]
It sounds like your game is crashing. Does this only happen when using the queue and not when rendering a single level?

**Comment by Andrey446** [comment]
This happens when the rendering queue settings are by default, except for the resolution that I changed to 1440p. For one song, everything is rendered normally.

**Comment by Metalit** [comment]
I meant, does it only crash if you render from the "begin queue" button in the settings? Or does it also crash if you press the render button on a level itself? Regardless of how many levels you have in the queue, if it's always on the first one anyway

**Comment by Andrey446** [comment]
Through the settings, start the problem queue. if at the very level, then everything is fine.

**Comment by Metalit** [comment]
Can you get a log of the crash?
Assuming you have sidequest installed:
1) Copy and paste the following into your file browser's address bar: `%appdata%\SideQuest\platform-tools`
    - Make sure that you have a file named `adb` or `adb.exe`
2) Hold shift, and while holding, right click somewhere blank in that folder
3) Click `Open command prompt` or `Open PowerShell` 
4) Connect your Quest to your computer
5) Write `.\adb.exe logcat > logcat.log` in that command line window that was opened and press enter 
    - Leave that window opened, and start the game on the Quest (while it is connected to your PC)
6) Then, play/fail a song, or any other thing that you need to get a log for, and take off your Quest
7) You can now close the command line window that you opened before
8) A file named logcat.log will be in the folder you opened first
9) Drag and drop that file into Github to upload the log file

**Comment by Andrey446** [comment]
I want to summarize my results.
What I have described is confusing, I think, and it may be difficult to understand.
1) If you add, say, 2 songs to the queue and go back to the start of the game to go into the settings and get to the replay mod.
Result:The black screen of Quest 2 was not heated and did not render anything.
2) If you add, say, 2 songs to the queue and click next to the gear that will lead to the replay mod settings.
Result:Everything works.

**Comment by Metalit** [comment]
I've made some changes to the queue, and since there's no specific information here, I'll close this.
