### ISSUE TITLE
Render Mod Won't Render Specific Song

### ISSUE THREAD

**Issue by Noiceb** [Metalit/Replay#63]
Map Link: https://beatsaver.com/maps/1fe6d

All other songs render fine with the mod, but when I try to render this song the first part of the render is just the replay playing at 60 fps at normal speed without audio. After it finishes the render and audio, nothing appears in the renders folder.

**Comment by Metalit** [comment]
Fixed by 5eb42033059207605f415151842c345bfe54a1e7, just need to make a new release sometime soon.
