### ISSUE TITLE
[suggestion] "render" audio only

### ISSUE THREAD

**Issue by rhysdh540** [Metalit/Replay#65]
make it so we can generate just the audio files in case it crashes while making them, but the video is generated fine

edit: you can also just use the raw audio from the song.egg file, but this would still be cool

**Comment by Metalit** [comment]
I would rather fix whatever's causing it to crash when making audio files, since the only potential crashes should be if the settings are too high and put too much load on the quest, and those settings don't apply when recording the audio

**Comment by rhysdh540** [comment]
I was rendering a noodle map with pretty high settings, so that was definitely the cause of the crash. Where would I find the crash report?

**Comment by Metalit** [comment]
Actually, if you crash during an audio render, it will render only the audio if you start another render. If it doesn't do that, then that means that it crashed while rendering the video, and if you take a closer look then it's probably cut off before the end of the level and you would need to render the video again anyway
