### ISSUE TITLE
(suggestion) Camera location presets

### ISSUE THREAD

**Issue by SH4WNATR0N** [Metalit/Replay#67]
I'm hoping I'm not dumb and this isnt already a feature but the ability to setup and save third person camera presets would be useful, I think. Like having and saving up to 5 third person camera positions that you can change between via the pause menu would be super useful i think, at least for editors and content creators.

**Comment by Metalit** [comment]
Not a bad idea, I'll see about doing something like this in the next update

**Comment by Inien65** [comment]
I’ll second this idea. 
A while ago I made this video to show off to friends. Rendering once in third person with avatar, then again with third person behind viewer for the inset, then combine in post. Just having presets would make this and the OP’s idea easier. 
https://youtu.be/AMhNeoxCojc?si=K6HkO7g2zSGMhwN2
