### ISSUE TITLE
Bringing back diffrent source render

### ISSUE THREAD

**Issue by ooTruffle** [Metalit/Replay#69]
For certan maps on a q2 beatsaber is crashing when it tries to load the map again for the auto
would there be a way for 
a. The user being able to just have the audio render and replay seeing the fnished video_temp before the crash and makeing the mp4
b. Replay if beatsaber crashes allowing someoe to "resume" a render
c. I if the audio and video are done seporately act like older verisons where it needs to ffmpeg to mp4

**Comment by Metalit** [comment]
After the video render finishes, a flag is set in the config to render audio next, which will persist even if the game crashes during the audio render. However, replay shouldn't cause the game to crash at all, regardless of map
