### ISSUE TITLE
Quest3 problem

### ISSUE THREAD

**Issue by Mqffin** [Metalit/Replay#72]
hello there i am new to the vr beat saber modding and now i saw the replay mod and wanted to try it out and after many trying songs and downloading multiple times the mod i cant seem to be able to use it at all . i have it on my settings menu but when i play and then leave the song the game doesnt show up the replay button how do i fix this?

**Comment by Metalit** [comment]
Rendering is broken on the quest 3 as in #70. Everything else should work as normal though, so refer to [the faq](https://github.com/Metalit/Replay#faq-frequently-asked-questions) for how to record replays.
