### ISSUE TITLE
Free 3rd Person movement is missing?

### ISSUE THREAD

**Issue by AK49BWL** [Metalit/Replay#73]
Way back on BS 1.13.2, I used the replay mod extensively, and I used to be able to move around freely by pressing A or X and moving my head in a certain direction. Unless I'm missing something, that appears to no longer be possible in v0.3.1, and movement is restricted to forward and backward while actively playing a replay?? Now if I set my "Movement Button" to A/X, pressing it allows me to turn and move minutely (not enough to get to the position I want), but upon letting go of the button the camera SNAPS to the default playing position. Am I missing something?

**Comment by Metalit** [comment]
It sounds like you're looking for the "Travel" buttons. Do they match what you're looking for?

**Comment by AK49BWL** [comment]
There is only Travel Forward and Travel Backward.. Those work as intended and the camera position stays, but there's no side to side nor pivot capability. And pressing and releasing the movement button just snaps me right back to default play position. Things worked as designed in mod v0.3.0 (not exactly free-motion but usable).

I've sort of worked around this issue by discovering the camera position is movable while the map is paused... That's helpful and allows me to get to a position I want to.

**Comment by Metalit** [comment]
Oh, it was working in 0.3.0 but changed in 0.3.1? I'll see if I can fix it in that case.

(When it works correctly, if you want more "free-motion" on the travel buttons, you can hold the movement button and either of them at the same time. I don't plan to add any side-to-side buttons because that would result in too many bindings.)

**Comment by AK49BWL** [comment]
Yes, that's how I moved around in 0.3.0 and it worked well enough.

Since I'm here I will say thank you for the time you've put into this mod, it's very well put together and useful :)

**Comment by dan-smith** [comment]
+1 re: "I used to be able to move around freely by pressing A or X and moving my head in a certain direction"
I too mega miss this feature, from the 'old' replay mod, for IIRC BS ~1.17.x, approx 2y ago.

To clarify, it was much like how you control those 'hoverboard' self-balancing scooters, but in 3D. For smoothly flying around the environment. If GitHub will allow a YouTube link, example (at timestamp in link), recorded in-headset: https://www.youtube.com/watch?v=RAXc-Emv_Z4&t=274s

Beers/coffees/doughnuts if fixed.
