### ISSUE TITLE
Trick Saber Support 

### ISSUE THREAD

**Issue by nis0808** [Metalit/Replay#76]
I tried to enjoy the map with Trick Saber and watch the replay, but Trick Saber's spinning and throwing tricks do not appear. I would appreciate it if you could fix it.

**Comment by Metalit** [comment]
Unfortunately this is not within the current plans for the mod, as it would require replay to have its own recorder with explicit compatibility for trick saber, neither of which are present at the moment

**Comment by Duffelsalat** [comment]
too bad, I would like to see this compatibility as well
