### ISSUE TITLE
Turn off current song text in replay

### ISSUE THREAD

**Issue by xseman** [Metalit/Replay#81]
Hi, thanks for the great mod!

I'm trying to figure out how to stop the current song from showing up in the replay **"REPLAY <song_name>"**.

My setup:
- Meta Quest 3
- Replay v0.3.2 (patched with QuestPatcher)

See the picture:

![image](https://github.com/Metalit/Replay/assets/9111485/0515a436-88bd-47d0-b6d4-16830d30d278)

**Comment by Metalit** [comment]
The text can only be disabled in locally saved replays, using the "Hide Player Text" setting.
