### ISSUE TITLE
1.35 Update

### ISSUE THREAD

**Issue by Slooshie1** [Metalit/Replay#85]
Are there any plans on making a version for Beat Saber 1.35?

**Comment by Metalit** [comment]
It's being worked on. There have been some issues with PC graphics in renders, so it will most likely come out after mods are released for 1.36.2+

**Comment by iroxOfficial** [comment]
> It's being worked on.

I thought you stopped updating and didnt give a crap, however i was wrong. Keep up the good work dude! :D

**Comment by beaudamion** [comment]
Can't wait for the update. 1.35+ crashes far less than prior versions and this is the only mod that I'm waiting for to update. Wish there was a mod like this for pc itself for lower end computers that can't run in realtime at 4k.
