### ISSUE TITLE
1.37 and audio desync

### ISSUE THREAD

**Issue by Xapherox** [Metalit/Replay#88]
I get that u haven't even updated for 1.35 yet, but, if they're simaler, could you update for 1.37 too? I just switched to it and want to be able to get videos of maps with a higher level fov. Also, when I was on 1.28 and using this mod, I rendered 4 videos. In all the videos, the audio was desynced and was moved foward by around half a second. I'm on standalone quest 3 if that helps. Ty

**Comment by hellGerra** [comment]
Try to increase resolution.

**Comment by Xapherox** [comment]
Kk
