### ISSUE TITLE
remove bitrate limit

### ISSUE THREAD

**Issue by christopher317** [Metalit/Replay#90]
for niche use cases that involve rendering at a VERY high frame rate ( ex: 300fps frame blending motion blur ), 100 megabit still isn't enough. being that those who are using a bitrate above 25 megabit are already modifying the config file to do so, why not remove the limit?

( edit: i haven't updated the mod in a while so if this has changed please let me know )

**Comment by RedGeometryDash** [comment]
i can confirm this hasn't changed as of the latest release, maybe remove the limit and add like a warning or something for the 1.37 update.

**Comment by Metalit** [comment]
I've removed the limit for the 1.37 update. Iirc I only added the config limit when I lowered the ingame limit because I didn't want people wasting storage without knowing about it, but since that was a few versions ago it's probably not a concern anymore
