### ISSUE TITLE
Can't find mod in game

### ISSUE THREAD

**Issue by hellGerra** [Metalit/Replay#91]
Hi, I installed new version for 1.37, but it is not displayed anywhere in the game and after song there is no way to save the replay.

**Comment by hellGerra** [comment]
There are no Hollywood in Mods anymore?

![FS Capture 20240723 070859](https://github.com/user-attachments/assets/1d8f8599-3e2f-4d64-a94a-31fabaafdac1)
![image_2024-07-23_071752610](https://github.com/user-attachments/assets/a1f66321-8cc2-434f-adfb-7b7c54c99318)

**Comment by Xapherox** [comment]
Do you have beat leder?

**Comment by hellGerra** [comment]
> Do you have beat leder?

Of course.

**Comment by hellGerra** [comment]
Oh, I re-install mod twice and Hollywood downloaded! It works!
