### ISSUE TITLE
No SFX in render

### ISSUE THREAD

**Issue by Slooshie1** [Metalit/Replay#93]
I have SFX enabled in replay's settings but the video was saved with the music being the only audio. I am using v0.3.3 on beat saber 1.37.0.

**Comment by OnQuest2** [comment]
Same issue here

**Comment by Xapherox** [comment]
Yeah, i have the same issue

**Comment by DeathShot984** [comment]
Aye, same here.

**Comment by AmeliaGL0w0** [comment]
> I have SFX enabled in replay's settings but the video was saved with the music being the only audio. I am using v0.3.3 on beat saber 1.37.0.

on the tab where you have video encoding settings, like resolution, bitrate etc, on top there is another tab, in which there is a setting to enable sfx (it makes the render process longer however)

**Comment by lordlad** [comment]
ditto...not audio sfx...only the music audio

**Comment by Azshurith** [comment]
Rendered this november, still no sfx.

**Comment by howarlii** [comment]
Is there any solution for this issue? I accidentally render a replay with SFX but I can't reproduce it.

**Comment by landozz** [comment]
im also encountering this issue, why doesnt the slider thats supposed to turn the sfx on do anything? do you have to have the slider on before you play a level or why cant the mod recreate the sfx in the render since its already in the replay file anyway?
