### ISSUE TITLE
Crashing when opening settings with a render queue

### ISSUE THREAD

**Issue by CodeTheWolf** [Metalit/Replay#94]
Version 1.37

game will crash when opening settings with a render queue

here’s crash logs: https://analyzer.questmodding.com/crashes/8Lf6

**Comment by VR-Nerd** [comment]
Cannot use replay at all. Every time I try to open it from the settings, it crashes the game.

**Comment by QueenLaqueefah** [comment]
Any possible updates on this bug or an ETA? It's still crashing the game unfortunately. And I luv this mod! Hoping it can be fixed soon! :)
