### ISSUE TITLE
[MP Bug] Capturing Multiplayer Host Saber Movement instead of the local Players movements.

### ISSUE THREAD

**Issue by GunnableScum** [Metalit/Replay#96]
This is an issue that happens with BeatTogether and MultiplayerCore installed only. If you join a multiplayer lobby and play a song, replay will capture the hosts saber movements instead of the local players movements.

This issue can be seen here, on a saved replay of mine on beatleader: https://replay.beatleader.xyz/?scoreId=17241544 (Warning: Explicit Song)

**Comment by NeoEliasTheDev** [comment]
i have the same issue.

**Comment by Metalit** [comment]
Issue with beatleader. https://github.com/BeatLeader/beatleader-qmod/commit/cddafd157ff0a8a0e67dbdb72e7fb4b00678536a

**Comment by GunnableScum** [comment]
Thanks for the clarification and sorry for bothering you, have a nice day!
