### ISSUE TITLE
[1.37] game crashes and replay isnt moved to the replay folder instead its left in the root called "temp"

### ISSUE THREAD

**Issue by SilvazWasTaken** [Metalit/Replay#97]
i dunno if this is meant to happen or-

**Comment by SilvazWasTaken** [comment]
thats what happened when i tried to render a replay for a song thats 4 seconds long anything longer and it just restarts the render when it finishes with no file

**Comment by Metalit** [comment]
Unless the crash is caused by replay, there isn't much I can do. You can send a crash log with the crash reporter if you think it is (ask in the bsmg discord #quest-help if you don't know how to get one), but it sounds more likely to have been caused by Qosmetics
